project: "BOTS-Selector"
name: "qwen2.5-1.5B-instruct-bots"
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
data_processor:
  experience_pipeline:
    operators:
      - name: pass_rate_calculator
algorithm:
  algorithm_type: grpo
  repeat_times: 16
  optimizer:
    lr: 1e-6
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-1.5B-Instruct}
  max_prompt_tokens: 4096
  max_response_tokens: 8192
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 32
  explorer_input:
    taskset:
      name: math-train
      storage_type: file
      path: 'your/data/path/containing/math__combined_54.4k.parquet' # you need to set it manually
      split: 'train'
      format:
        prompt_key: 'prompt'
        response_key: 'reward_model.ground_truth'
      rollout_args:
        temperature: 1.0
      task_selector:
        selector_type: difficulty_based
        feature_keys: [ "qwen2.5_7b_pass_rate", "qwen3_30b_pass_rate" ]
        kwargs:
          m: 16
          lamb: 0.1
          rho: 0.1
          target_reward: 0.5
          tau: 0
          do_sample: true
    eval_tasksets:
    - name: math-eval
      storage_type: file
      path: 'your/data/path/containing/math__math_500.parquet' # you need to set it manually
      format:
        prompt_key: 'prompt'
        response_key: 'reward_model.ground_truth'
      rollout_args:
        temperature: 1.0
    default_workflow_type: 'examples.bots.workflow.bots_math_boxed_workflow.BOTSMathBoxedWorkflow'
  trainer_input:
    experience_buffer:
      name: exp_buffer
      storage_type: queue
      path: 'sqlite:///bots_trainer_buffer.db'
explorer:
  eval_interval: 40
  runner_per_model: 8
  rollout_model:
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 8
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  save_interval: 800
  grad_clip: 1.0
  use_dynamic_bsz: true
  max_token_len_per_gpu: 24576
  ulysses_sequence_parallel_size: 1
