project: "bots_ref_eval_collect_demo_1.5B"
name: "run-1"
mode: explore
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: grpo
  repeat_times: 16
  optimizer:
    lr: 1e-6
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-1.5B-Instruct}
  max_prompt_tokens: 4096
  max_response_tokens: 8192
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 100
  explorer_input:
    taskset:
      name: math-train
      storage_type: file
      path: 'your/data/path/containing/math__combined_54.4k.parquet' # you need to set it manually
      split: 'train'
      format:
        prompt_key: 'prompt'
        response_key: 'reward_model.ground_truth'
      rollout_args:
        temperature: 1.0
      task_selector:
        selector_type: sequential
    default_workflow_type: 'bots_ref_eval_collect_math_boxed_workflow'
  trainer_input:
    experience_buffer:
      name: exp_buffer
      storage_type: queue
      path: 'sqlite:///bots_ref_eval_collect_buffer.db'
explorer:
  eval_interval: 100
  runner_per_model: 16
  rollout_model:
    engine_num: 8
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 10
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  save_interval: 1000
  grad_clip: 1.0
  use_dynamic_bsz: true
  max_token_len_per_gpu: 24576
  ulysses_sequence_parallel_size: 1
