project: Trinity-RFT-example
name: dapo
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-1.5B-Instruct}
  max_response_tokens: 20480
  max_model_len: 21504
algorithm:
  algorithm_type: grpo
  repeat_times: 16
  optimizer:
    lr: 1e-6
    lr_warmup_steps: 20
  policy_loss_fn_args:
    clip_range_low: 0.2
    clip_range_high: 0.28
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 32
  explorer_input:
    taskset:
      name: dapo-math
      storage_type: file
      path: open-r1/DAPO-Math-17k-Processed
      subset_name: all
      format:
        prompt_key: 'prompt'
        response_key: 'solution'
        system_prompt: 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.'
      rollout_args:
        temperature: 1.0
        logprobs: 0
      workflow_args:
        use_base: true
      reward_fn_args:
        enable_overlong_penalty: true
        penalty_factor: 1.0
        max_response_length: 20480
        cache_length: 4096
    eval_tasksets:
    - name: AIME2024
      storage_type: file
      path: HuggingFaceH4/aime_2024  # Path to the AIME2024 dataset
      split: 'train'
      repeat_times: 32
      format:
        prompt_key: 'question'
        response_key: 'answer'
        system_prompt: 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.'
      rollout_args:
        temperature: 1.0
        top_p: 0.7
    default_workflow_type: 'math_boxed_workflow'
    default_reward_fn_type: 'math_dapo_reward'
  trainer_input:
    experience_buffer:
      name: math_buffer
      storage_type: queue
explorer:
  eval_interval: 10
  runner_per_model: 8
  rollout_model:
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 16
  sync_timeout: 1200
trainer:
  save_interval: 100
  grad_clip: 1.0
  use_dynamic_bsz: true
  max_token_len_per_gpu: 22000
  ulysses_sequence_parallel_size: 1
