project: "FrozenLake"
name: "Qwen2.5-3B-Instruct-agent"
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: multi_step_grpo
  repeat_times: 16
  kl_loss_fn: "low_var_kl"
  kl_loss_fn_args:
    kl_coef: 0
  advantage_fn_args:
    epsilon: 1e-6
    std_threshold: 0.0001
    enable_step_norm: true
  optimizer:
    lr: 1e-6
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-3B-Instruct}
  max_response_tokens: 2048
  max_model_len: 25600
  temperature: 1.0
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 32
  train_batch_size: 1024
  explorer_input:
    taskset:
      name: frozenlake
      storage_type: file
      path: ${oc.env:TRINITY_TASKSET_PATH}
      split: train
      workflow_args:
        env_max_steps: 8
        agent_max_steps: 10
        is_slippery: false
    default_workflow_type: 'examples.agentscope_frozenlake.workflow.FrozenLakeWorkflow'
  trainer_input:
    experience_buffer:
      name: frozenlake_experience_buffer
      storage_type: queue
      max_read_timeout: 7200
      replay_buffer:
        enable: true
        priority_fn: linear_decay
        priority_fn_args:
          decay: 0.1
explorer:
  eval_on_startup: true
  eval_interval: 20
  runner_per_model: 8
  rollout_model:
    engine_num: 6
    tensor_parallel_size: 1
    enable_chunked_prefill: true
    enforce_eager: false
    enable_openai_api: true
    enable_log_requests: true
    enable_history: true
    enable_auto_tool_choice: true
    tool_call_parser: hermes
    # reasoning_parser: deepseek_r1  # if you use Qwen3 series, uncomment this line
    enable_thinking: true
    dtype: bfloat16
    seed: 42
    gpu_memory_utilization: 0.85
trainer:
  save_interval: 100
  use_dynamic_bsz: true
  grad_clip: 1.0
  ulysses_sequence_parallel_size: 2

synchronizer:
  sync_method: nccl
  sync_style: explorer_driven
  sync_interval: 1
  sync_timeout: 1200
