project: "Trinity-RFT-toolace"
name: "qwen2.5-7B-toolace"
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: grpo
  repeat_times: 8
  optimizer:
    lr: 1e-6
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen1.5-7B-Chat}
  max_response_tokens: 8192
  max_model_len: 12288
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 128
  explorer_input:
    taskset:
      name: toolace_data
      storage_type: file
      path: examples/grpo_toolcall/toolace_data
      # format: []
      rollout_args:
        temperature: 1.0
        logprobs: 0
      default_workflow_type: 'toolcall_workflow'
  trainer_input:
    experience_buffer:
      name: toolace_buffer
      storage_type: queue
      path: 'sqlite:///toolace.db'
explorer:
  eval_interval: 50
  runner_per_model: 8
  rollout_model:
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 1
  sync_timeout: 3600
trainer:
  save_interval: 100
  grad_clip: 1.0
  use_dynamic_bsz: true
  max_token_len_per_gpu: 16384
  ulysses_sequence_parallel_size: 2
